name: ci
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Document Version'     
        required: true
        default: '0.2.0'
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.PORT }}
            script: cd /data/matrixorigin.io 
                    && git fetch --all 
                    && git reset --hard origin/main 
                    && git pull 
                    && git submodule update --init
                    && git submodule update --remote
                    && git commit -m "update submodules" || echo "No changes to commit"
                    && git push
                    && mike deploy --push --update-aliases ${{ github.event.inputs.version }} latest
                    && git add *
                    && git commit * -m "update site"
                    && git push
